databases:
  - name: land-rnr
    user: land-rnr
    plan: free
    region: ohio

services:
  - type: web
    name: land-rnr
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: land-rnr
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false