databases:
  - name: land_rnr
    user: land_rnr
    plan: free
    region: ohio

services:
  - type: web
    name: land_rnr
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: land_rnr
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false